Update for issue: #23 cli authentication
Update for issue: https://github.com/csev/dj4e/issues/23

Undecided if more info is too much, "Create a PAT" is, https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

In the instructions, likely changes in branch name to main, creating a blank repo in GitHub the startup code has changed, a new line, the -M main,

git commit -m "first commit"
git branch -M main
git remote add origin 

without, as PYAW Settings defaults to (master) and GitHub Repository default branch is main

22:37 ~/django_projects (master)$ git remote add origin https://github.com/--your-account--/django_projects.git
22:40 ~/django_projects (master)$ git push -u origin main
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/srcedx/django_projects.git'

with

22:40 ~/django_projects (master)$ git branch -M main
22:41 ~/django_projects (main)$ git push -u origin main
Username for 'https://github.com':